### ISSUE TITLE
Extra type families in `fromF`

### ISSUE THREAD

**Issue by ilyakooo0** [bolt12/laop#13]
https://github.com/bolt12/laop/blob/9a79218b15e420d8e4b7ba95f84e3b213709fd20/src/LAoP/Matrix/Internal.hs#L442-L443

It seems like this should be:

```haskell
Proxy :: Proxy (Count a)
```

, since all `Normalize` seems to do is convert a type into its' `Either`/`()` representation, keeping the same `Count`.

So it would seem like 

```haskell
Count (Normalize a) ~ Count a
```

What am I missing here?

**Comment by bolt12** [comment]
Yes you're right, I might have been too concentrated on the types and didn't realize that `Count (Normalize a) ~ Count a`. Thanks for pointing it out!

**Comment by ilyakooo0** [comment]
If that's the case, then it would seem like the `N` versions of these types are redundant:

https://github.com/bolt12/laop/blob/9a79218b15e420d8e4b7ba95f84e3b213709fd20/src/LAoP/Matrix/Internal.hs#L233-L236

**Comment by bolt12** [comment]
They are not, unfortunately we still need them for `(><)` and `fstM`, `sndM`, `kr` . But we can greatly simplify the other functions constraints :smile:

**Comment by bolt12** [comment]
I'll close this since I think I covered all the redundant cases! :) thanks for opening this issue!
